[project]
name = "apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# Support Python 3.10 through 3.12.
requires-python = ">=3.10,<3.13"
dependencies = [
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
]
