
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AnalyticsPage = lazy(() => import("./pages/AnalyticsPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ClientProfilePage = lazy(() => import("./pages/ClientProfilePage.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const PipelinePage = lazy(() => import("./pages/PipelinePage.tsx"));
const TasksPage = lazy(() => import("./pages/TasksPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/analytics-page", element: <AnalyticsPage />},
	{ path: "/analyticspage", element: <AnalyticsPage />},
	{ path: "/", element: <App />},
	{ path: "/client-profile-page", element: <ClientProfilePage />},
	{ path: "/clientprofilepage", element: <ClientProfilePage />},
	{ path: "/login-page", element: <LoginPage />},
	{ path: "/loginpage", element: <LoginPage />},
	{ path: "/pipeline-page", element: <PipelinePage />},
	{ path: "/pipelinepage", element: <PipelinePage />},
	{ path: "/tasks-page", element: <TasksPage />},
	{ path: "/taskspage", element: <TasksPage />},

];
